project_name: traefik-wasm-query-param-check
version: 2

builds:
  - id: plugin
    skip: true

# before hooks removed: run TinyGo build manually (instructions below)

archives:
  - id: plugin
    name_template: '{{ .ProjectName }}_v{{ .Version }}'
    formats: [zip]
    files:
      - src: LICENSE
        dst: LICENSE
      - src: .traefik.yml
        dst: .traefik.yml
      - src: plugin.wasm
        dst: plugin.wasm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs: '
      - '^doc: '
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'
