name: Release (goreleaser)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release via goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TinyGo (manual)
        run: |
          set -eux
          TGV=0.39.0
          ARCH=amd64
          URL="https://github.com/tinygo-org/tinygo/releases/download/v${TGV}/tinygo${TGV}.linux-${ARCH}.tar.gz"
          echo "Downloading TinyGo from $URL"
          curl -fsSL "$URL" -o /tmp/tinygo.tar.gz
          sudo tar -C /usr/local -xzf /tmp/tinygo.tar.gz
          sudo ln -sf /usr/local/tinygo/bin/tinygo /usr/local/bin/tinygo
          tinygo version

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: --version

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
