name: Release (goreleaser)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release via goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TinyGo
        uses: tinygo-org/setup-tinygo@v0.5.0
        with:
          version: '0.34.0'

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: --version

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
